# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-wrangler" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "e06be4b601f3a7b558c672e0bb3b75be84d1af50e1e537f6eaf0f7b9c5149725"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a9353293ac8e47c6e7de62cd1704f174b713ccd6b3040b416b72dbc55c771a5"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2c12a14b48fb060c36559c3a26afdf92dcea05944539cf79e017b9b4b0d83ea"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88d7a6f2f1e838bb47ae22e51c8b0e415e79aa878f6987e59cafe0e24ccd27af"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-wrangler"
  desc "Orchestrate Git operations across many repositories."
  homepage "https://github.com/kaufmann-dev/git-wrangler"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
      "git-filter-repo",
    ]

  binary "git-wrangler"
  bash_completion "completions/git-wrangler.bash"
  fish_completion "completions/git-wrangler.fish"
  zsh_completion "completions/git-wrangler.zsh"

  # No zap stanza required

  caveats <<~EOS
    Run `git-wrangler init` before private or all GitHub repository operations.
    History rewrite commands use git-filter-repo and rewrite Git history.
  EOS
end
