# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-wrangler" do
  version "0.5.10"

  on_macos do
    on_intel do
      sha256 "57692ddccd8811f18fa5b49a685275e23a38b424f25ca574eff1e1cfa6bf0c34"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54c6c89b2ea70c3b528f4e38a5e3bba7ceef97cafd14007e4e26398d59aa62ef"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c20fbcde9ac5eb8b612da93eb3830273e4642d55a33e713169fa9872a6ce98d"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd2d395cb8d01901139a5977ac1157bb1a7ba98ed6a2b6b68c835c0ddf33cdf2"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-wrangler"
  desc "Orchestrate Git operations across many repositories."
  homepage "https://github.com/kaufmann-dev/git-wrangler"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
      "git-filter-repo",
    ]

  binary "git-wrangler"
  bash_completion "completions/git-wrangler.bash"
  fish_completion "completions/git-wrangler.fish"
  zsh_completion "completions/git-wrangler.zsh"

  # No zap stanza required

  caveats <<~EOS
    Run `git-wrangler init` before private or all GitHub repository operations.
    History rewrite commands use git-filter-repo and rewrite Git history.
  EOS
end
