# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-wrangler" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "fb3e17f12fae6af664c0705f8c48b5369ff4893a759516918f73cb0665de6411"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da77cf6bdbfc6fde761d95ce4da784ff9129dde4cbd56b96d7de354b15fffb0d"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ddab7f41f6a1f2058e276dfe7a73a47d9cd4be2e9fb238e6e85b9713fc2c002a"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "703d06b7b035c0473a64ac5763046b7c10690d5e8e48c35e69d3446636096dda"
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v#{version}/git-wrangler_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-wrangler"
  desc "Orchestrate Git operations across many repositories."
  homepage "https://github.com/kaufmann-dev/git-wrangler"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
      "git-filter-repo",
    ]

  binary "git-wrangler"
  bash_completion "completions/git-wrangler.bash"
  fish_completion "completions/git-wrangler.fish"
  zsh_completion "completions/git-wrangler.zsh"

  # No zap stanza required

  caveats <<~EOS
    Run `git-wrangler init` before private or all GitHub repository operations.
    History rewrite commands use git-filter-repo and rewrite Git history.
  EOS
end
