# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWrangler < Formula
  desc "Orchestrate Git operations across many repositories."
  homepage "https://github.com/kaufmann-dev/git-wrangler"
  version "0.2.0"
  license "MIT"

  depends_on "gh"
  depends_on "git"
  depends_on "git-filter-repo"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.2.0/git-wrangler_0.2.0_darwin_amd64.tar.gz"
      sha256 "18c4c32f447ef0357129ff6bcd72e387ad37acbff9c1ef5ee1dc77a3e6fe8225"

      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.2.0/git-wrangler_0.2.0_darwin_arm64.tar.gz"
      sha256 "7d3b964b8dc3e8d3d2ab12206505be59478bb1b2e1cafadbc43f2b8d37e353ab"

      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.2.0/git-wrangler_0.2.0_linux_amd64.tar.gz"
      sha256 "b673c0b7501aa3294e50c272118717c14449d018d6175421c73070fb9993df06"
      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.2.0/git-wrangler_0.2.0_linux_arm64.tar.gz"
      sha256 "722d06e68262b42c0f8a22a543ce7cbb1bfaa2d6890c911d1bad548cfc0d3f4f"
      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Run `gh auth login` before private or all GitHub repository operations.
      History rewrite commands use git-filter-repo and rewrite Git history.
    EOS
  end

  test do
    system "#{bin}/git-wrangler", "version"
  end
end
