# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWrangler < Formula
  desc "Orchestrate Git operations across many repositories."
  homepage "https://github.com/kaufmann-dev/git-wrangler"
  version "0.1.0"
  license "MIT"

  depends_on "gh"
  depends_on "git"
  depends_on "git-filter-repo"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.1.0/git-wrangler_0.1.0_darwin_amd64.tar.gz"
      sha256 "33cc57d68f9b0514b6468797e6fdba87e902b8cd07deac3e0dff8a1529ad7623"

      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.1.0/git-wrangler_0.1.0_darwin_arm64.tar.gz"
      sha256 "f880b35ab50474a9d433ad4042468a236203f4f2dd60fc00f76ff94297b1ea3e"

      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.1.0/git-wrangler_0.1.0_linux_amd64.tar.gz"
      sha256 "e396918eb46d4298037b8d5ab4213bf345fd90a862fd1930fa3d4b879b8aa7bd"
      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kaufmann-dev/git-wrangler/releases/download/v0.1.0/git-wrangler_0.1.0_linux_arm64.tar.gz"
      sha256 "f486a4268471afc781809c53d0b3338bff02b2fc38cd0b562b01486ab87184d8"
      def install
        bin.install "git-wrangler"
        bash_completion.install "completions/git-wrangler.bash" => "git-wrangler"
        zsh_completion.install "completions/git-wrangler.zsh" => "_git-wrangler"
        fish_completion.install "completions/git-wrangler.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Run `gh auth login` before private or all GitHub repository operations.
      History rewrite commands use git-filter-repo and rewrite Git history.
    EOS
  end

  test do
    system "#{bin}/git-wrangler", "version"
  end
end
